# Part I: History of the Doctrine of Justification

This history of the doctrine of justification[^1]

[^1]: Many years ago, Bishop O\'Brien announced his intention to prepare a History of the Doctrine of Justification; but that intention has not yet been carried into effect, and there is scarcely any work in the English language which can be said to supply the want. It is in every respect desirable, that one so thoroughly competent for the task, in point both of ability and learning, should take up this comprehensive subject, which can only be treated cursorily in a series of Lectures like the present, and would require an entire volume for its illustration.

    The sources of information on the subject are either general or special. Some works give the history of the doctrine,---or materials for constructing its history,---in all ages, including the faith of the Church in regard to it under the Old, as well as the New, Dispensation;---others give its history, either in the Old Testament, or in post-apostolic times, only.
    
    To the first class belong the Scriptures of the Old and New Testaments, which must ever have the first place assigned to them, as being inspired records, both of the divine revelations which were vouchsafed from time to time to the Church, and of the faith and worship which were maintained in it from the beginning. A sound exposition of Scripture, which should follow the historical course of Revelation from its commencement to its close in the sacred canon, would be the best history of both.
    
    The \'Magdeburg Centuriators,\'---viz., M. Flacius Illyricus, Joannes Wigandus, Matthæus Judex, Basilius Faber, and others who were associated with them,---were induced to write the History of the Church anew by the conviction, that previous historians had not given due prominence to the doctrinal truths of Scripture, especially to the doctrine of Justification; and they have collected valuable materials for its history, both under the Old dispensation and the New. Two of their number,---Joannes Wigandus and Matthæus Judex,---published separately from their great work, in 1563, a thick quarto volume, entitled, \'SYNTAGMA, seu Corpus Doctrinœ ex Veteri Testamento tantùm Collectum,\' in which they collect together, under distinct heads, the great truths which are common to both Testaments; and treat \'De Evangelio,\' p. 944, \'De Justificatione Peccatoris coram Deo,\" p. 962, \'De Fide,\' p. 1003, \'De Bonis Operibus,\' p. 1019, and other cognate topics. In their larger work, the Centuriators give the history of the doctrine under the New Testament dispensation, but not continuously; the passages which relate to it must be collected from the account of each century. Century I., Book i. c. iv., includes the teaching of our Lord, pp. 9--111, and of the Apostles, pp. 219--278, \'De Justificatione Hominis coram Deo;\' and the same topic is resumed in each successive century.
    
    The two works of Buddeus,---\'Historia Ecclesiastica Veteris Testamenti,\' and \'Ecclesia Apostolica,\'---embrace the teaching of both Testaments. Four admirable \'Exercitations,\' by Witsius, give the history of the opinions which prevailed among the Gentiles and the Jews; also the doctrine which was taught by the Apostles: \'Miscell. Sacra,\' vol. ii. pp. 668--752. They are entitled, respectively,---\'De Theologia Gentilium in Negotio Justificationis,\' pp. 668--697,---\'De Theologia Judæorum in Negotio Justificationis,\' pp. 698--721,---\'De Controversiis quæ Apostolorum ætate in Ecclesia Christiana circa Justificationem ortæ sunt,\' pp. 721--731,---\'De Mente Pauli in Negotio Justificationis,\' pp. 732--752. These dissertations were occasioned by Dr. Cave\'s \'Antiquitates Apostolicæ,\' on that work being translated and published on the Continent; and were designed as an answer to it. Dr. Cave\'s opinion was, that the doctrine, as taught by the Apostles, excluded Justification by ceremonial observances, and left it to depend entirely on Faith; but that this Faith, which is the only condition of the New Covenant, is not any special grace, having an office or function distinct from that of other graces, but is rather comprehensive of them all; and that, therefore, works of evangelical obedience are not excluded from the ground of our acceptance with God. To this class of works may be added President Edwards\' \'History of Redemption.\'
    
    The works which have been mentioned afford materials for constructing the history of the doctrine in the Church both of the Old and New Testaments. Many other works give, more or less fully, the history of the doctrine either in the Old Testament, or in post-apostolic times. Of works on the Old Testament, we may mention, Hengstenberg\'s \'Christology of the Old Testament,\' 4 vols. (T. and T. Clark, Edinburgh), with the older \'Christology\' of Robert Fleming, jun.; and that most instructive and edifying series of Lectures, in 4 vols., entitled, \'Christ as made known to the Ancient Church,\' by my late venerable colleague, Dr. Gordon, of the High Church, Edinburgh. Of works relating to the post-apostolic History of the Doctrine, we may mention, Dr. Hagenbach, of Basle, \'Compendium of the History of Doctrines,\' vol. ii. pp. 267--274, and 447--460; Dr. Shedd, of America, \'History of Christian Doctrine,\' Book v. \'History of Soteriology,\' vol. ii. pp. 201--386; Dr. Muenschen, of Marpurg, \'Elements of Dogmatic History,\' translated by Dr. James Murdoch, 1830, c. vii. pp. 72--80, and 184--190.
    
    Petavius does not treat of Justification as a distinct topic in his \'Dogmata Theologica\' (6 vols. fol., Antwerp, 1700), but frequent references occur to it; as when he speaks of \'Preparations for Justification,\' vol. i. lib. x. c. xxvii. s. 12,---of \'Justice,\' or \'Righteousness,\' vol. i. lib. vi. c. viii. s. 6; lib. x. c. ii. s. 4, c. xiv. s. 1,---of \'Justification and Adoption,\' vol. ii. lib. viii. c. 4, 5, 10, 1; in vol. iii. \'De Pelagianis et Semipelagianis,\' p. 336, and \'De Tridentini Concilii Interpretations,\' and \'De Sancti Augustini Doctrina,\' p. 353, when he refers to the conflicting interpretations by Soto and Vega of the Canons and Decrees of the Council, c. xv.; and in vol. v. vi. \'De Incarnation Verbi,\' in 16 books.
    
    One of the most useful works on the subject is that of J. Forbes (of Corse), \'Instructiones Historico-Theologicæ.\' See lib. viii. c. 2, 5--10, but especially c. 23, 24, pp. 423--429.
    
    Chemnitz gives \'Veterum Testimonia de Justifications\' in the first part of his \'Examen Concilii Tridentini,\' p. 141.
    
    All the general histories of the Church may be consulted, such as Dr. Kurtz\'s \'History of the Old Covenant,\' and Neander\'s, Weismann\'s, Mosheim\'s, and Milner\'s, Histories of the Christian Church.
    
    The special sources of information, in regard to the state of the doctrine at particular eras, will be referred to in connection with each of the great controversies which have arisen in regard to it. But full information cannot be obtained by merely reading an historical narative; and recourse must be had to two or three of the best writers on each side of every discussion, as it passes under review.