[]{#doctrinejustification_split_009.html}

### []{#doctrinejustification_split_009.html#lectures .calibre7}INDEX TO THE LECTURES ONLY {.calibre4}

------------

For the Appendix, see the Numerals inserted in each Lecture, which refer to corresponding Notes.

------------

ABRAHAM, The Justification of, 34, 51, 53, 244.

Adoption, 210, 211, 261.

Ambrose, 94.

Amesius, 142.

Amyraldus, 175.

Andradius, 142.

Andrewes, Bishop, 199.

Anselm, 96, 112.

Anti-Neonomians, 177, 182.

Antinomianism, 153, 157, 158--161, 201.

Arian doctrine of Justification, 165--168.

Arminian doctrine of Justification, 170--173, 175, 176, 178, 200, 218.

Arminius, Sentiments of, 171.

Arminians, Pelagian and Evangelical, 173, 178.

Articles of Church of England, 193, 194, 198.

Assurance, 184, 376.

Athanasius, 94.

Atterbury, Bishop, 143, 200.

Augustine, The doctrine of, 88, 95, 112.

---------His use of the term \'Merits,\' 90.

---------His use of the term \'Justification,\' 91.

Augsburg, Diet of, 127, 129.

---------\'Confession\' and \'Apology,\' 128.

---------Reply to, by Faber and Eckius, 128.

BAIUS, 112, 146, 148.

Barclay, Robert, \'Apology\' of, 169.

Barlow, Bishop, 199.

Barnes, Albert, 190.

Baro, 200.

Barrow, 200.

Barrott, 200.

Basil, 94.

Baxter, Richard, 176.

Bellarmine, 142, 199, 213.

Bennett, Dr. James, \'Justification as Revealed in Scripture,\' 13, 92, 215.

Bernard, A saying of, 92.

---------His doctrine of Justification, 96.

Beveridge, Bishop, 199.

Blanc, Louis le, 148, 200.

Boos, Martin, 149.

Bossuet, 143, 144, 154, 200.

Boston, Rev. Thomas, 183.

Boyd, of Trochrig, 174, 175.

Bucer, 131, 136, 138, 195, 196, 201.

Bull, Bishop, 291.

Burnet, Bishop, 200, 218.

CAJETAN, 112, 135.

Calvin, Antidote of, 141.

---------On Osiander, 155.

---------On Stancari, 156.

---------On Antinomianism, 157, 202.

---------On Justification, 194, 196.

Camero, 174.

Carleton, Bishop, Reply to Bishop Montagu, 200.

Cave, Dr., 201.

Chalmers, Dr. T., on \'Justification by Faith,\' and \'Judgment according to Works,\' 238.

Charles v., 131, 135.

Chemnitz, \'Examen,\' 141, 142.

Church of England, Articles of, 10.

Chrysostom, 95.

Circumcision, Discussion as to the necessity of, 68, 70, 73.

Clemens Romanus, 83.

Contarenus, 114.

\'Counsels of Perfection,\' 106.

Covenant, The first, of Life, 19.

---------The second, of Grace, 24, 33.

Cranmer, 195.

Crisp, Dr., 176, 183.

Cunningham, Dr., Testimony of, to Church of England, 192.

Cyprian, 94.

DAVENANT, Bishop, 92, 142, 199.

Davenport, Dr., or Francis à Sancta Clara, 144, 145, 200, 204.

Dezius, of Strasburg, 144.

Diognetus, Epistle to, 85.

Doctrine of Paul and James, 239--249.

Dort, Synod of, 174, 200.

Downham, Bishop, 92, 142, 199.

Du Pin, 131, 148.

ECKIUS, Reply to Augsburg \'Confession,\' 128, 131.

Erasmus, Work of, on \'Concord in Religion,\' 130.

\'Essays and Reviews,\' 218.

FABER, G. S., \'Primitive Doctrine of Justification,\' 12, 92, 93, 215.

---------On the exercise of private judgment, 79.

Faber and Eck, Reply to Melancthon\'s Confession, 128.

Faith, Function of, in Justification, 364, 379.

---------It is not our justifying righteousness, 366.

---------Its nature, as a spiritual grace, 373, 375.

---------Only, the means of Justification, 384.

Fathers, the right use of their writings, 77.

---------The state of the question in regard to their doctrine of Justification, 78.

---------The Apostolical, 81.

---------Testimonies of, collected by Usher and Faber, 93.

Fisher, E., author of \'Marrow of Modern Divinity,\' 182.

Forbes, J., of Corse, 91.

Fox, the Quaker, 169.

Foxe, John, the Martyrologist, 143, 198.

Fraser, of Brea, 187.

Francis, St., \'Conformities of,\' 144.

French Protestant Church, 174.

Friends, Society of, 168, 211.

GENTILES, state of, 36, 47, 50, 60.

Gill, Dr., Notes on Crisp\'s Sermons, 183.

God\'s chief end, 289, 312.

Goodwin, John, 175.

Grace, The import of, 339.

---------Not inconsistent with Redemption, 340.

Gropper, The work of, 130, 131, 136, 197.

Grotius, 148.

HADOW, Principal, 182, 184.

Hermann, Archbishop of Cologne, 130, 136.

Herrnhutt, 181.

History of the Doctrine, 1--219.

---------In the Old Testament, 1--45, 54.

---------Under the Patriarchal Dispensation, 35.

---------Under the Mosaic Law, 37.

---------Under the Prophets, 41.

---------In the Apostolic Age, 46.

---------How the Apostles reasoned with the Jews, 51, 63.

---------How our Lord dealt with them, 61.

---------Controversies concerning Justification in the Primitive Church, 66, 68, 69, 74.

---------In the times of the Fathers and Scholastic Divines, 77.

---------The Protestant Doctrine not a \'novelty,\' 88, 93, 135.

---------At the Reformation, 100.

---------The chief means of effecting the Reformation, 100.

---------In the Romish Church after the Reformation, 127.

---------Protestant Doctrine treated at a \'novelty,\' 128.

---------Afterwards claimed as an old truth, 129, 138, 140.

---------Difference between Romish and Reformed doctrine, 148, 149.

---------Among Protestants, 151, 154.

---------In the Church of England, 192.

---------Declension in the Church of England, 199, 217.

---------Causes of Declension, 199--203.

---------Changes in, 217--220.

---------Prospects of, 218.

Hoadley, Bishop, 201.

Hodge, Dr., 190, 410.

Hopkinsian Doctrine, 190.

Hog, Rev. James, of Carnock, 182.

Homilies of Church of England, 193, 198.

Hooker, 199.

Huss, 112, 181.

IGNATIUS, 84.

Imputation of sin, 279, 321.

---------Of righteousness, 321, 334.

---------Three cases of, in Scripture, 323.

---------Not a Theory, but a Fact, 337.

Incarnation, The, made to supersede the Mediatorial work of Christ, 205, 207, 303.

Indulgences, 99, 100.

---------History of, 103--108.

---------Controversy on, 111.

Interim, The, 138.

Irenæus, 93.

JANSENIUS, 146.

Jansenists, 112, 183.

Jerome, of Prague, 181.

Jerome, 95.

Jewish Church, Corruption of, 51.

---------Opinions which prevailed in, 55.

Judgment, private, the exercise of, 79.

Justice of God, 269, 288.

Justification, the Doctrine of, why selected, 1, 14, 15.

---------The Influence of, on the Reformation, 9.

---------The Protestant Doctrine of, recently assailed, 10.

---------Definition of, 17, 255.

---------Of the righteous, 18.

---------Of sinners, 24.

---------As taught in the Jewish Church, 57.

---------As held by the Gentiles, 63.

---------All human systems of, similar, 65.

---------As taught in Church of Rome, 113, 124.

---------Nature of, 114.

---------Ground of, 116.

---------Means of, 118.

---------Effect of, 122.

---------Best preparation for the study of, 222.

---------The meaning of the term, 226.

---------Actual and Declarative, 233.

---------Doctrine of Paul and James, 239.

---------Nature of the Blessing, 250.

---------Includes Pardon and Acceptance, 251.

---------Justification and Sanctification differ, 265.

---------Its relation to the Law and Justice of God, 268.

---------Its relation to the Work of Christ, 292.

---------Its Immediate Ground, 314.

---------Its relation to Grace, 339.

---------Its relation to Works, 350, 358.

---------Its relation to Faith, 365.

---------Its relation to the Work of the Spirit, 387.

---------Originality of the Scripture Doctrine, 407.

Justin Martyr, 85.

KAYE, Bishop, 195.

Kingsley, Rev. C., 205.

Knox, John, 196.

Knox, Alexander, Esq., \'Remains,\' 11, 205, 211.

---------Correspondence with Bishop Jebb, 11, 205.

LAUD, Archbishop, 217.

Lauterwald, 155.

Laurence, Archbishop, 200.

Law, the, Primeval, 20, 269, 270.

---------The Mosaic, 37.

Law, cannot be relaxed, 283, 284.

Law, the, and the Gospel, 291.

Legalism, natural tendency to, 153.

\'Legal Fictions,\' 334.

Leibnitz, 148.

Luther on Justification, 129, 194, 196.

---------Remarks of, 129, 130, 149, 150, 204.

---------Anticipated declension from his Doctrine, 153, 204.

---------On Antinomianism, 157, 202.

MARROW CONTROVERSY, 182--188.

Martyr, Peter, 196, 197, 201.

Mass, the, 111.

Maurice, Rev. F., 205.

Mediatorial Work of Christ, 292, 301.

---------As substitute and surety of His people, 298, 395.

Mediatorial Law, 300.

Melville, Andrew, 174.

Melancthon, on works of supererogation, 99.

---------\'Confession\' and \'Apology,\' 128, 129.

---------Remarks of, 130, 138, 155, 156, 157.

---------His Doctrine on Justification, 131, 194--7.

---------His \'Prolegomena\' on Justification, 197.

---------His \'Loci Communes,\' 197.

Merit, Doctrine of, 99, 106, 142.

Methodists, New, of France, 173, 175, 176, 202.

---------Wesleyan, 176, 178--181.

Merit of Christ, 321.

Molinæus (du Moulin), 174.

Mœhler on \'Symbolism,\' 145, 147, 199.

Montagu, Bishop, Appeal of, 200, 201.

Moravian Brethren, 181.

NEONOMIANISM, 176--178, 202.

Neo-Platonic School of Theology, 205, 207, 211.

Newhaven Theology, 190.

Newman, Dr. J. H., \'Lectures on Justification,\' 13, 207.

---------\'Apologia pro Vita Sua,\' 13.

---------\'Essay on Development,\' 147.

---------\'Via Media,\' 213.

OBEDIENCE OF CHRIST, active and passive, 307.

O\'Brien, Bishop, \'Essays on Faith,\' 12, 92.

Originality of the Gospel method of Justification, 405.

Origen, 95.

Original sin, 279.

Osiander, 1, 155.

Osorio, 142, 198.

Oxford, the two Schools of Theology in, 218.

PARDON, Romish Doctrine of, 103, 256.

Parker, Archbishop, 217.

Penn, William, 169.

Paternity and Sonship, relation of, 207.

Pharisees, the Doctrine of, on Justification, 66, 71.

Philosophy, the Doctrine of Justification corrupted by, 75, 83, 86, 97.

Pflug, 131.

Piscator, 157, 174, 175.

Pistorius, 131.

Popery, Old and New, 143.

Princeton \'Review\' and \'Essays,\' 190.

Priesthood, a human, 109.

Promise, the first, 24.

Psalms, the Book of, 42.

Pusey, Dr., 204, 206.

QUAKERS, the Doctrine of, 168.

Quesnel, 112, 146.

RATIONALISM, 4, 5, 218.

Ratisbon, Diet of, 129.

---------Attempted compromise at, 131, 133.

---------Lessons of, 136.

Repentance, how related to Justification, 385.

Reunion of Protestants with Rome, 144.

Regeneration and Justification simultaneous, 400, 403.

Rhemish New Testament, 144.

\'Righteousness, the, of God,\' 315, 317.

Ridley, 195, 196.

Ritualism, 4, 7, 218.

Robertson, Rev. F. W., of Brighton, 205.

Ryder, Dr., Donnellan Lectures, 206, 216.

SACRIFICE, origin and import of, 28, 47, 49.

Sacrifice of the Altar, 110.

Sandemanian Doctrine, 188--190.

Satisfaction of Christ, 308, 310.

Scholastic Theology, 98.

---------Errors of, on Justification, 99, 100, 105.

Socinianism, 157, 161--165.

Spangenberg, 181.

Spiritualists, Modern, 169.

Soto, 144.

Stancari, 156.

Stuart, Moses, 190.

TAYLOR, ISAAC, \'Ancient Christianity, 13.

Tendencies, Natural, towards Legalism, or Antinomianism, 153, 157, 203.

Tertullian, Remark of, 154.

Tilenus, D., 174, 175.

Tillotson, Archbishop, 218.

\'Tracts for the Times,\' 13, 204, 218.

Traill, Rev. Robert, 14, 173.

Trent, the Council of, not the only authority, 112, 145.

---------Its Decrees and Canons, 138, 139.

Trinity, Doctrine of, revealed by the work of Redemption, 294.

---------Distinct parts of the work ascribed to the Father, Son, and Spirit, 294, 389.

UNANIMITY of Reformers on Justification, 151.

\'Unitas Fratrum,\' 181.

Universal Redemption, 187.

Usher, Archbishop, 92, 93.

VARIATIONS of Popery and Protestantism, 154.

Vasquez, 142.

Vega, 144.

Vergerio, Bishop, converted by answering Reformers, 135.

\'Via Media\' between Popish and Protestant Doctrine, 205, 213.

Vincentius Lirinensis, Rule of, 147.

WAKE, Archbishop, 142, 158, 200.

Warrant of Faith, 187, 380.

Welsh, John, 174, 175.

Wesel, 112.

Wesley, John, 180, 218.

Westminster Doctrine of Justification, 411.

Whately, Archbishop, \'Errors of Romanism,\' 204.

Whitfield, George, 218.

Wickliffe, 112.

Work of the Holy Spirit in applying Redemption, 387.

---------Not the ground of Justification, 393.

Works; what works excluded from Justification, 67, 349, 353.

---------None can justify, 277, 343, 345.

ZINZENDORF, Count, 181.

Zuingle, 194.

\-\-\-\--